export enum tagTypes {
  auth = 'auth',
  user = 'user',
  superAdmin = "superAdmin",
  admin = "admin",
  manager = "manager",
  customer = "customer",
  department = "department",
  category = "category",
  subCategory = "subCategory",
  childCategory = "childCategory",
  product = "product",
  order = "order",
  brand = "brand",
  unit = "unit",
  attribute = "attribute",
  tax = "tax",
  role = "role",
  permission = "permission",
  businessUnit = "businessUnit",
  supplier = "supplier",
  purchase = "purchase",
  settings = "settings",
  outlet = "outlet",
  attributeGroup = "attributeGroup",
  StorefrontConfig = "StorefrontConfig",
  StorePage = "StorePage",
  StorePageList = "StorePageList",
}

export const tagTypesList = Object.values(tagTypes);
