export const ROUTE_PATHS = {
  DASHBOARD: {
    ROOT: "",
  },
  BUSINESS_UNITS: {
    ROOT: "business-units",
    NEW: "business-units/new",
    ANALYTICS: "business-units/analytics",
  },
  OUTLETS: {
    ROOT: "outlets",
    NEW: "outlets/new",
  },
  LOGISTICS: {
    ROOT: "logistics",
    COURIER: "logistics/courier",
    PARCEL: "logistics/parcel",
    REPORTS: "logistics/reports",
  },
  RISK: {
    ROOT: "risk",
    FRAUD: "risk/fraud",
    BLACKLIST: "risk/blacklist",
    RULES: "risk/rules",
    ANALYTICS: "risk/analytics",
  },
  USER_MANAGEMENT: {
    ROOT: "user-management",
    ALL_USERS: "user-management/all-users",
    PLATFORM_USERS: "user-management/users",
    ROLES_PERMISSIONS: "user-management/roles-permissions",
    ADD_USER: "user-management/add-user",
    // PLATFORM_USERS defined above
    USER_DETAILS: (id: string) => `user-management/users/${id}`,
  },
  CATALOG: {
    ROOT: "catalog",
    PRODUCT: {
      ROOT: "catalog/product",
      ADD: "catalog/product/add",
      EDIT: "catalog/product/edit",
    },
    CATEGORY: "catalog/category",
    SUB_CATEGORY: "catalog/sub-category",
    CHILD_CATEGORY: "catalog/child-category",
    BRAND: "catalog/brand",
    UNIT: "catalog/unit",
    ATTRIBUTE: "catalog/attribute",
    ATTRIBUTE_GROUP: "catalog/attribute-groups",
    TAX: "catalog/tax",
    WARRANTY: "catalog/warranties", // Added warranty path
  },
  INVENTORY: {
    ROOT: "inventory",
    PURCHASE: "inventory/purchase",
    PURCHASE_NEW: "inventory/purchase/new",
    ADJUSTMENTS: "inventory/adjustments",
    LEDGER: "inventory/ledger",
    WAREHOUSES: "inventory/warehouses",
    TRANSFERS: "inventory/transfers",
    ALERTS: "inventory/alerts",
  },
  PURCHASES: {
    ROOT: "purchases",
  },
  SALES: {
    ROOT: "sales",
    POS: "pos",
    TODAY: "sales/today",
    SHIPPING: "sales/shipping",
    DELIVERY: "sales/deliveries",
    RETURNS: "sales/returns",
    INVOICES: "sales/invoices",
  },
  MARKETING: {
    ROOT: "marketing",
    PROMOTIONS: "marketing/promotions",
    COUPONS: "marketing/coupons",
    CAMPAIGNS: "marketing/campaigns",
    AFFILIATES: "marketing/affiliates",
    LOYALTY: "marketing/loyalty",
    SEO: "marketing/seo",
    PIXEL: "marketing/pixel",
    AUDIENCES: "marketing/audiences",
  },
  CUSTOMERS: {
    ROOT: "customers",
    NEW: "customers/new",
    LOYALTY: "customers/loyalty",
    SUBSCRIPTIONS: "customers/subscriptions",
    REVIEWS: "customers/reviews",
    WISHLISTS: "customers/wishlists",
    CARTS: "customers/carts",
  },
  SUPPORT: {
    ROOT: "support",
    TICKETS: "support/tickets",
    CHAT: "support/chat",
    DISPUTES: "support/disputes",
  },
  CONTENT: {
    ROOT: "content",
  },
  FINANCE: {
    ROOT: "finance",
    PAYMENTS: "finance/payments",
    SETTLEMENTS: "finance/settlements",
    PAYOUTS: "finance/payouts",
    FRAUD: "finance/fraud",
    REPORTS: "finance/reports",
    ANALYTICS: "finance/analytics",
    AUDIT_LOGS: "finance/audit-logs",
  },
  SYSTEM: {
    ROOT: "system",
    AUDIT_LOGS: "system/audit-logs",
    NOTIFICATIONS: "system/notifications",
    LANGUAGES: "system/languages",
    CURRENCIES: "system/currencies",
    ZONES: "system/zones",
    BACKUPS: "system/backups",
    API_KEYS: "system/api-keys",
    WEBHOOKS: "system/webhooks",
    EMAIL_TEMPLATES: "system/email-templates",
    SMS_TEMPLATES: "system/sms-templates",
  },
  SUPPLIERS: {
    ROOT: "suppliers",
  },
  REPORTS: {
    ROOT: "reports",
    SALES: "reports/sales",
    PURCHASES: "reports/purchases",
    STOCK: "reports/stock",
    PROFIT_LOSS: "reports/profit-loss",
    EXPENSE: "reports/expenses",
  },
  STAFF: {
    ROOT: "staff",
  },
  HRM: {
    ROOT: "hrm",
    STAFF: "hrm/staff",
    DEPARTMENTS: "hrm/departments",
    DESIGNATIONS: "hrm/designations",
    ATTENDANCE: "hrm/attendance",
    LEAVE: "hrm/leave",
    PAYROLL: "hrm/payroll",
    ASSETS: "hrm/assets",
  },
  ACCOUNTING: {
    ROOT: "accounting",
    ACCOUNTS: "accounting/accounts",
    TRANSACTIONS: "accounting/transactions",
    EXPENSES: "accounting/expenses",
    BUDGETS: "accounting/budgets",
    TAX: "accounting/tax",
  },
  VENDORS: {
    ROOT: "vendors",
    ONBOARDING: "vendors/onboarding",
    PAYOUTS: "vendors/payouts",
  },
  POS_CONFIG: {
    ROOT: "pos-config",
    TERMINALS: "pos-config/terminals",
    REGISTERS: "pos-config/registers",
  },
  STOREFRONT: {
    ROOT: "online-store",
    UI_BUILDER: "online-store/ui-builder",
    PAGES: "online-store/pages",
    THEMES: "online-store/themes",
    PLUGINS: "online-store/plugins",
    LANDING_PAGES: "online-store/landing-pages",
    SETTINGS: "online-store/settings",
  },
  POS: {
    QUICK_SALES: "quick-sales",
    TODAY: "today",
    MY_SALES: "my-sales",
  },
  COMMON: {
    NOTIFICATIONS: "notifications",
    PROFILE: "profile",
    SETTINGS: "settings",
    HELP: "help",
  }
} as const;
